server:
  port: 8000
spring:
  application:
    name: demo
  jpa:
    open-in-view: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
        cache.region.factory_class: org.hibernate.cache.EhCacheRegionFactory
    generate-ddl: false
    hibernate: 
      ddl-auto: update
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
logging: 
   level:
     root: info
